package com.yunjishi.lixiang.yunjishi.presenter.database;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.yunjishi.lixiang.yunjishi.presenter.data.bean.UserBean;
import com.yunjishi.lixiang.yunjishi.presenter.data.bean.UserBean2;

import com.yunjishi.lixiang.yunjishi.presenter.database.UserBeanDao;
import com.yunjishi.lixiang.yunjishi.presenter.database.UserBean2Dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig userBean2DaoConfig;

    private final UserBeanDao userBeanDao;
    private final UserBean2Dao userBean2Dao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        userBean2DaoConfig = daoConfigMap.get(UserBean2Dao.class).clone();
        userBean2DaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        userBean2Dao = new UserBean2Dao(userBean2DaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(UserBean2.class, userBean2Dao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        userBean2DaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public UserBean2Dao getUserBean2Dao() {
        return userBean2Dao;
    }

}
